"""add password_hash to users

Revision ID: 770c6ed0c8a3
Revises: 3cca7ad9e4f4
Create Date: 2026-05-12 18:45:20.877295

"""
from alembic import op
import sqlalchemy as sa


revision = '770c6ed0c8a3'
down_revision = '3cca7ad9e4f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###